# Generated by Django 2.2 on 2026-02-28 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('persuader', 'Persuader'), ('target', 'Target')], default='target', max_length=20)),
                ('seed_inputs_json', models.TextField(default='{}')),
                ('profile_data_json', models.TextField(default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonaState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stance_score', models.FloatField(default=3.0)),
                ('memory_summary', models.TextField(default='')),
                ('open_objections_json', models.TextField(default='[]')),
                ('session_count', models.IntegerField(default=0)),
                ('last_outcome_label', models.CharField(default='', max_length=50)),
                ('trigger_active', models.BooleanField(default=False)),
                ('next_trigger_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='sim_core.PersonaProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('persuader_goal', models.TextField(default='')),
                ('context_json', models.TextField(default='{}')),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='CREATED', max_length=20)),
                ('conversation_log', models.TextField(default='[]')),
                ('session_number', models.IntegerField(default=1)),
                ('is_autonomous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SimulationDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('outcome_label', models.CharField(default='', max_length=50)),
                ('rationale', models.TextField(default='')),
                ('stance_delta', models.FloatField(default=0.0)),
                ('memory_summary', models.TextField(default='')),
                ('new_objections_json', models.TextField(default='[]')),
                ('next_step', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scenario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='sim_core.Scenario')),
            ],
        ),
        migrations.AddField(
            model_name='scenario',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='sim_core.SimulationDomain'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='persona_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenarios', to='sim_core.PersonaState'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='target_persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenarios_as_target', to='sim_core.PersonaProfile'),
        ),
        migrations.AddField(
            model_name='personaprofile',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='sim_core.SimulationDomain'),
        ),
    ]
