# Generated by Django 2.2 on 2026-02-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banker_idea', models.TextField(help_text='The idea the banker wants to propose.')),
                ('client_persona', models.TextField(help_text='JSON representation or description of the client persona.')),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='CREATED', max_length=20)),
                ('conversation_log', models.TextField(default='[]', help_text='JSON list of conversation turns.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
