# Generated by Django 2.2 on 2026-02-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_sim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='client_industry',
            field=models.CharField(default='General', help_text='Industry of the client (e.g. Technology, Manufacturing)', max_length=100),
        ),
        migrations.AddField(
            model_name='scenario',
            name='financial_context',
            field=models.TextField(default='Stable financials', help_text='Key financial data (Revenue, eBook, etc.)'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='market_conditions',
            field=models.TextField(default='Neutral market', help_text='Current market environment (e.g. Bull/Bear, high interest rates)'),
        ),
    ]
